### ISSUE TITLE
Import doesn't work with YAML files

### ISSUE THREAD

**Issue by j-vizcaino** [mickep76/etcdtool#12]
When I try to import a YAML into etcd, the imported content is broken.
Digging into the code, I have found that the problem lies in `etcdmap.Create`.

It seems, `json` and `toml` return some sort of `map[string]interface{}` whereas `yaml` returns a `map[interface{}]interface{}`. This is causing a lot of trouble and an issue has been opened for `go-yaml`  (see https://github.com/go-yaml/yaml/issues/139, someone posted a workaround for this)

Here is an example that shows the problem:

```go
package main

import (
  "fmt"
  "reflect"
  "encoding/json"
  "gopkg.in/yaml.v2"
)

func test(doc interface{}) {
  fmt.Println(doc)
  v := reflect.ValueOf(doc)
  fmt.Printf("Kind: %v\n", v.Kind())
  for _, k := range v.MapKeys() {
    fmt.Println(k.String())
  }
}


func main() {

  var doc interface{}

  fmt.Println("=== YAML ===")
  yaml.Unmarshal([]byte("a: b"), &doc)
  test(doc)

  fmt.Println("=== JSON ===")
  json.Unmarshal([]byte(`{"a":"b"}`), &doc)
  test(doc)
}
```

Run this and you should see:

```
=== YAML ===
map[a:b]
Kind: map
<interface {} Value>     <===== !!!!
=== JSON ===
map[a:b]
Kind: map
a
```

**Comment by mickep76** [comment]
Thanks, for the bug report. I'll have a look later prob. today as time allows and see if the proposed workaround might be a solution. Or maybe I can resort to another library.

**Comment by mickep76** [comment]
Sorry for the late response, I had a look and the only workaround that seems feasable is the one suggested in the thread you included: https://github.com/elastic/beats/blob/6435194af9f42cbf778ca0a1a92276caf41a0da8/libbeat/common/mapstr.go

I looked at other YAML Parsers, but they are not fully featured or unmaintained.

I'll have a look on adding the workaround above.

**Comment by mickep76** [comment]
Included MapStr workaround as part of branch: https://github.com/mickep76/iodatafmt/tree/fix-yaml-mapstr

I will merge it once it's done.

**Comment by mickep76** [comment]
Fixed in the latest "iodatafmt" package.

**Comment by j-vizcaino** [comment]
Thanks !
