### ISSUE TITLE
Cannot import empty directories

### ISSUE THREAD

**Issue by JacobHayes** [mickep76/etcdtool#13]
Importing json with an empty directory skips that directory. For example, importing the following json:
```json
{"empty_dir":{},"dir":{"key":"value"}}
```
results in:
```
/
└── dir/
    └── key
```

I thought this might be related to matching Go's default value if a dir is unmarshalled into an empty map, but I'm not sure because keys with empty string values are imported correctly.

**Comment by JacobHayes** [comment]
Looking at the code a bit more, this might have been more appropriate for mickep76/etcdmap. It doesn't handle creating a directory for an empty map [here](https://github.com/mickep76/etcdmap/blob/master/etcdmap.go#L256). I might try that out and make a PR tonight if I get a chance.

**Comment by mickep76** [comment]
As you say it doesn't handle empty directories. Is there a point in having a directory without any values in it?

**Comment by mickep76** [comment]
It should be relatively easy too fix thought.

**Comment by mickep76** [comment]
This should fix it: https://github.com/mickep76/etcdmap/commit/3c21b353a973d94ee6a5baee448c18f990a82d64

Need to test it thoroughly before merging it thought.

**Comment by JacobHayes** [comment]
Yes, I have a cluster of nodes that register in a given directory. When setting up the scaffolding, that dir should be empty, since no nodes are registered.

That seems like it would do it! I'll test it out and get back to you. One nit: for structs and maps you use string concatenation for creating `dir`, but use `fmt.Sprintf` for slices. Also, thanks for etcdtool, it's been very handy, especially during prototyping!

**Comment by JacobHayes** [comment]
Aah, actually the creation of the directory needs happen before the loop with just `path`, as long as it's not the root. Currently it creates a directory for every item in the iterable, even if it's just a value. This patch from master works for me:

```
diff --git a/etcdmap.go b/etcdmap.go
index 0c8c290..624ecbe 100644
--- a/etcdmap.go
+++ b/etcdmap.go
@@ -229,6 +229,21 @@ func Array(root *client.Node, dirName string) []interface{} {
 	return v
 }
 
+// createDir will create path if it doesn't exist and is not root.
+func createDir(kapi client.KeysAPI, path string) error {
+	if path != "/" {
+		if _, err := kapi.Set(context.TODO(), path, "", &client.SetOptions{Dir: true, PrevExist: client.PrevNoExist}); err != nil {
+			if etcdErr, ok := err.(client.Error); ok {
+				if etcdErr.Code == client.ErrorCodeNodeExist {
+					return nil
+				}
+			}
+			return err
+		}
+	}
+	return nil
+}
+
 // Create etcd directory structure from a map, slice or struct.
 func Create(kapi client.KeysAPI, path string, val reflect.Value) error {
 	switch val.Kind() {
@@ -246,6 +261,7 @@ func Create(kapi client.KeysAPI, path string, val reflect.Value) error {
 			return err
 		}
 	case reflect.Struct:
+		createDir(kapi, path)
 		for i := 0; i < val.NumField(); i++ {
 			t := val.Type().Field(i)
 			k := t.Tag.Get("etcd")
@@ -257,6 +273,7 @@ func Create(kapi client.KeysAPI, path string, val reflect.Value) error {
 		if strings.HasPrefix(pathx.Base(path), "_") {
 			log.Printf("create hidden directory in etcd: %s", path)
 		}
+		createDir(kapi, path)
 		for _, k := range val.MapKeys() {
 			v := val.MapIndex(k)
 			if err := Create(kapi, path+"/"+k.String(), v); err != nil {
@@ -264,6 +281,7 @@ func Create(kapi client.KeysAPI, path string, val reflect.Value) error {
 			}
 		}
 	case reflect.Slice:
+		createDir(kapi, path)
 		for i := 0; i < val.Len(); i++ {
 			Create(kapi, fmt.Sprintf("%s/%d", path, i), val.Index(i))
 		}
```

with the following json:
```json
{
  "service": {
    "list": [
      1,
      2
    ],
    "list-empty": [],
    "object": {
      "string": "value"
    },
    "object-empty": {},
    "string": "value"
  }
}

```

**Comment by JacobHayes** [comment]
Also, the etcd repo restructured so that the client libraries can be imported without using their vendored version. I left it unchanged here since etcdtool still has the old layout.

**Comment by mickep76** [comment]
Thanks for the testing and patch, I'll test it and merge it on Mon.
