### ISSUE TITLE
Password support

### ISSUE THREAD

**Issue by davewalk** [mickep76/etcdtool#16]
We would love to use this tool programmatically, but running into issues with passing the password. Would you be open to a PR that added support for using a flag or environment variables or something else? I'm willing to work on it, just wanted to get your thoughts on the best strategy.

Thanks!

**Comment by mickep76** [comment]
Should be fairly simple, for security it would be pref. to use a file
rather then argument or env.

**Comment by mickep76** [comment]
Something like:

etcdtool --password-file <file> ...

**Comment by davewalk** [comment]
And the file would just be:

    password

?

**Comment by mickep76** [comment]
The file would contain the password, the reason for this is that you can
restrict perm. of a file. Where as an argument may be visible in ps.

**Comment by davewalk** [comment]
Gotcha, ok, I'll start working on this

**Comment by mickep76** [comment]
Cool, just give me a pull req once it's done.
