### ISSUE TITLE
yes/no is ignored on `import --replace --yes`

### ISSUE THREAD

**Issue by ytjohn** [mickep76/etcdtool#20]
When doing an import with --replace --yes, you still get asked if you want to overwrite.  Looking at the code, I can't tell if this is intentional or an oversight.  I can override this behavior by piping the word "yes" to the program, but I think that it would make more sense for --yes to  "Answer yes to any questions".

Context: goal is to store files representing specific directories in git, going through PR review process, and on change, commit those to etcd.

**Comment by mickep76** [comment]
The difference is that without --replace it will only overwrite i.e. not delete existing content first as you probably already realized. If it still ask for confirmation that is most likely a bug, I'll have a look in the coming days.

**Comment by ytjohn** [comment]
Understood. Yes, I wanted to delete existing keys if they don't exist in the file (the file being the ultimate authority).  Thank you.

**Comment by mickep76** [comment]
This is the problem if we replace it doesn't consider the arguments.

I'll issue a patch.

/Michael

```go
if exists {
		if replace {
			if !askYesNo(fmt.Sprintf("Do you want to overwrite data in directory: %s", dir)) {
				os.Exit(1)
			}

			// Delete dir.
			if _, err = ki.Delete(context.TODO(), dir, &client.DeleteOptions{Recursive: true}); err != nil {
				fatal(err.Error())
			}
		} else {
			if !yes {
				if !askYesNo(fmt.Sprintf("Do you want to overwrite data in directory: %s", dir)) {
					os.Exit(1)
				}
			}
		}
```

**Comment by mickep76** [comment]
Bunped a v3.4 should fix the issue.
