### ISSUE TITLE
Build with CGO_ENABLED=0 and netgo?

### ISSUE THREAD

**Issue by kramvan1** [mickep76/etcdtool#24]
quote from: https://dominik.honnef.co/posts/2015/06/statically_compiled_go_programs__always__even_with_cgo__using_musl/

The second solution, which most people go for, is to avoid cgo altogether. They use the netgo tag to build a pure-Go version of the net package, and they set CGO_ENABLED=0. Of course this has the drawback of not being able to use cgo. That means you can’t even use os/user to get the name of the current user.

remove dependency on glibc for this tool?

**Comment by mickep76** [comment]
Why?
